description: Creating an app deployment will pull the latest changes from your repository
  and schedule a new deployment for your app.
operationId: create_deployment
parameters:
- description: The app ID
  in: path
  name: app_id
  required: true
  schema:
    type: string
requestBody:
  content:
    application/json:
      schema:
        $ref: models/apps_create_deployment_request.yml
  required: true
  x-originalParamName: body
responses:
  "200":
    $ref: responses/new_app_deployment.yml
  "401":
    $ref: ../../shared/responses/unauthorized.yml
  "500":
    $ref: ../../shared/responses/server_error.yml
  default:
    $ref: ../../shared/responses/unexpected_error.yml
summary: Create an App Deployment
tags:
- Apps
