description: Retrieve information about an app deployment.
operationId: get_deployment
parameters:
- description: The app ID
  in: path
  name: app_id
  required: true
  schema:
    type: string
- description: The deployment ID
  in: path
  name: deployment_id
  required: true
  schema:
    type: string
responses:
  "200":
    $ref: responses/list_deployment.yml
  "401":
    $ref: ../../shared/responses/unauthorized.yml
  "500":
    $ref: ../../shared/responses/server_error.yml
  default:
    $ref: ../../shared/responses/unexpected_error.yml
summary: Retrieve an App Deployment
tags:
- Apps
