description: List all deployments of an app.
operationId: list_deployments
parameters:
- description: The app ID
  in: path
  name: app_id
  required: true
  schema:
    type: string
- $ref: ../../shared/parameters.yml#/page
- $ref: ../../shared/parameters.yml#/per_page
responses:
  "200":
    $ref: responses/existing_deployments.yml
  "401":
    $ref: ../../shared/responses/unauthorized.yml
  "500":
    $ref: ../../shared/responses/server_error.yml
  default:
    $ref: ../../shared/responses/unexpected_error.yml
summary: List App Deployments
tags:
- Apps
