DomainName:
  name: domain_name
  description: The name of the domain itself.
  in: path
  schema:
    type: string
  example: example.com
  required: true

DomainNameQuery:
  name: name
  description: >-
    A fully qualified record name. For example, to only include records matching
    sub.example.com, send a GET request to 
    `/v2/domains/$DOMAIN_NAME/records?name=sub.example.com`.
  in: query
  schema:
    type: string
  example: sub.example.com

DomainTypeQuery:
  name: type
  description: 'The type of the DNS record. For example: A, CNAME, TXT, ...'
  in: query
  schema:
    type: string
    enum:
      - A
      - AAAA
      - CAA
      - CNAME
      - MX
      - NS
      - SOA
      - SRV
      - TXT
  example: A
